project:
  type: website

website:
  title: "Women+ ECR Symposium"
  navbar:
    background: "#6A1B9A"   # deep purple
    foreground: white
    left:
      - href: index.html
        text: Home
      - href: about.html
        text: About
      - href: schedule.html
        text: Programme

# TOP-LEVEL SETTINGS
output-dir: _site
clean-url: true

format:
  html:
    theme:
      - cosmo
      - brand
      - styles.scss
    css: styles.css
    toc: true

editor: visual



