project:
  type: website
  output-dir: docs
  resources:
    - assets/womenplus_ecr_latex.zip
    - images/


website:
  title: "Women+ ECR Symposium"
  navbar:
    logo: images/logo_dark_bkg.png
    logo-height: 50px
    background: "#291957"   # deep purple
    foreground: white
    left:
      - href: index.html
        text: Home
      - href: about.html
        text: About
      - href: schedule.html
        text: Programme
      - href: contacts.qmd
        text: Contacts
# TOP-LEVEL SETTINGS
output-dir: _site
clean-url: true

format:
  html:
    theme:
      - cosmo
      - brand
      - styles.scss
    css: styles.css
    toc: true

editor: visual



