project:
  type: website

website:
  title: "Women+ ECR Symposium"
  navbar:
    background: "#6A1B9A"   # deep purple
    foreground: white
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - schedule.qmd

format:
  html:
    theme:
      - cosmo
      - brand
      - styles.scss
    css: styles.css
    toc: true

editor: visual

